

package old.api;

import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author emanion
 */
public class SimpleDateWindow extends javax.swing.JFrame {

    /**
     * Creates new form SimpleDateWindow
     */
    public SimpleDateWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrompt = new javax.swing.JLabel();
        txtDateString = new javax.swing.JTextField();
        btnStoreDate = new javax.swing.JButton();
        lblStringDate = new javax.swing.JLabel();
        lblPromptTwo = new javax.swing.JLabel();
        txtDateStringTwo = new javax.swing.JTextField();
        lblDateDiffLabel = new javax.swing.JLabel();
        lblDateDiff = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrompt.setText("Enter Order Date");

        txtDateString.setText("...");

        btnStoreDate.setText("Store Order");
        btnStoreDate.setActionCommand("");
        btnStoreDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreDateActionPerformed(evt);
            }
        });

        lblStringDate.setText(".......");

        lblPromptTwo.setText("Enter Second Date");

        txtDateStringTwo.setText("....");

        lblDateDiffLabel.setText("Difference Days");

        lblDateDiff.setText(".....");

        jLabel4.setText("**Dates in MM/DD/YYY format");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStringDate)
                            .addComponent(btnStoreDate)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrompt)
                                    .addComponent(lblPromptTwo)
                                    .addComponent(lblDateDiffLabel))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDateDiff)
                                    .addComponent(txtDateString, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(txtDateStringTwo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrompt)
                    .addComponent(txtDateString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnStoreDate)
                .addGap(38, 38, 38)
                .addComponent(lblStringDate)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromptTwo)
                    .addComponent(txtDateStringTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateDiffLabel)
                    .addComponent(lblDateDiff))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreDateActionPerformed
        Order order = new Order();
        String dateValue = txtDateString.getText();
        String dateValueTwo = txtDateStringTwo.getText();
        try {
            order.setOrderDateFromString(dateValue, "M/d/yyy");  //lower m = milliseconds
            lblStringDate.setText(lblStringDate.getText() + order.getOrderDate());
            // below code is to convert dates and calc diff.
            // step 1 - convert both Strings to a Date object -  first is done above.
            order.setDateTwoFromString(dateValueTwo, "M/d/yyy");
            // step 2 - convert both Dates to a Calendar object.
            order.setOrderDateCal();   //will set Calender ojbect for orderDate
            order.setDateTwoCal();     //will set Calendar object for dateTwo
            // step 3 - calc days diff using Calendar objects.
            double daysDiff = order.getDaysDiff();       //will calc difference
            // step 4 -  set output label field with calculated difference
            lblDateDiff.setText(Double.toString(daysDiff));
            
        } catch (ParseException ex) {
        JOptionPane.showMessageDialog(this, "Sorry you must enter a date in the format needed");
        return;
        }
        
    }//GEN-LAST:event_btnStoreDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleDateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleDateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleDateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleDateWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleDateWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStoreDate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDateDiff;
    private javax.swing.JLabel lblDateDiffLabel;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JLabel lblPromptTwo;
    private javax.swing.JLabel lblStringDate;
    private javax.swing.JTextField txtDateString;
    private javax.swing.JTextField txtDateStringTwo;
    // End of variables declaration//GEN-END:variables
}
